apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha
  labels:
    arxen.io/managed: "true"
    arxen.io/tenant-id: "11111111-1111-1111-1111-111111111111"
    arxen.io/compliance-tier: "soc2"
    arxen.io/environment: "dev"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-without-limits
  namespace: team-alpha
spec:
  containers:
    - name: app
      image: nginx:1.25.3
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-requests-only
  namespace: team-alpha
spec:
  containers:
    - name: app
      image: nginx:1.25.3
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-limits
  namespace: team-alpha
spec:
  containers:
    - name: app
      image: nginx:1.25.3
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-initcontainer-without-limits
  namespace: team-alpha
spec:
  initContainers:
    - name: setup
      image: nginx:1.25.3
  containers:
    - name: app
      image: nginx:1.25.3
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
