apiVersion: v1
kind: Namespace
metadata:
  name: regulated-ns
  labels:
    arxen.io/managed: "true"
    arxen.io/compliance-tier: "soc2"
    arxen.io/tenant-id: "22222222-2222-2222-2222-222222222222"
    arxen.io/environment: "prod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-no-pdb-annotation
  namespace: regulated-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mycompany.azurecr.io/apps/backend:v2.1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-pdb-annotation
  namespace: regulated-ns
  annotations:
    arxen.io/pdb: "managed"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mycompany.azurecr.io/apps/backend:v2.1.0
